# Generated by Django 3.2.4 on 2021-06-06 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorisation_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='history',
            field=models.ManyToManyField(blank=True, to='main.Video', verbose_name='History'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Subscriptions'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
