# Generated by Django 3.2.4 on 2021-06-04 11:45

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Avatar'),
        ),
    ]
