# Generated by Django 3.2.4 on 2021-06-03 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Subscriptions'),
        ),
    ]
