# Generated by Django 3.2.4 on 2021-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation_user', '0002_auto_20210603_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
