# Generated by Django 3.2.4 on 2021-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_likeordislike_vote'),
        ('authorisation_user', '0002_alter_advuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='history_video',
            field=models.ManyToManyField(blank=True, related_name='history', to='main.Video', verbose_name='History'),
        ),
    ]
