# Generated by Django 3.2.4 on 2021-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_likeordislike_vote'),
        ('authorisation_user', '0003_advuser_history_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='history_video',
        ),
        migrations.AddField(
            model_name='advuser',
            name='history',
            field=models.ManyToManyField(blank=True, to='main.Video', verbose_name='History'),
        ),
    ]
