# Generated by Django 3.2.4 on 2021-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation_user', '0005_alter_advuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='', verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
