# Generated by Django 3.2.4 on 2021-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation_user', '0006_alter_advuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='About me'),
        ),
    ]
