# Generated by Django 3.2.4 on 2021-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=None, upload_to='', verbose_name='Video'),
            preserve_default=False,
        ),
    ]
