# Generated by Django 3.2.4 on 2021-06-04 11:42

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=main.utilities.get_timestamp_path, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Preview'),
        ),
    ]
