# Generated by Django 3.2.4 on 2021-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subscriptions_views',
            field=models.BigIntegerField(default=0, verbose_name='With subscription views'),
        ),
    ]
