# Generated by Django 3.2.4 on 2021-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210604_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAndDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[(-1, 'dislike'), (1, 'like')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
