# Generated by Django 3.2.4 on 2021-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='new-games', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
