# Generated by Django 3.2.4 on 2021-06-04 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210604_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeanddislike',
            options={'verbose_name': 'Like or Dislike', 'verbose_name_plural': 'Likes or Dislikes'},
        ),
        migrations.AddField(
            model_name='likeanddislike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='act', to='authorisation_user.advuser', verbose_name='User'),
            preserve_default=False,
        ),
    ]
