# Generated by Django 3.2.4 on 2021-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210604_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanddislike',
            name='vote',
            field=models.CharField(choices=[('dislike', 'dislike'), ('like', 'like')], max_length=10),
        ),
    ]
