# Generated by Django 3.2.4 on 2021-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210604_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeordislike',
            options={'verbose_name': 'Like or Dislike', 'verbose_name_plural': 'Likes or Dislikes'},
        ),
        migrations.AlterField(
            model_name='likeordislike',
            name='vote',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=10, verbose_name='Vote'),
        ),
    ]
