# Generated by Django 3.2.4 on 2021-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210604_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeordislike',
            name='vote',
            field=models.CharField(max_length=10, verbose_name='Vote'),
        ),
    ]
