# Generated by Django 3.2.4 on 2021-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_likeordislike_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
