# Generated by Django 3.2.4 on 2021-06-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments_on',
            field=models.BooleanField(default=True, verbose_name='Comments on?'),
        ),
        migrations.AddField(
            model_name='video',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private video?'),
        ),
    ]
